<?php

  require_once("../FPDF/fpdf.php");
  require_once("../db.php");
  session_start();

class PDF extends FPDF {

  // Page header
function Header()
{

    // Arial bold 15
    $this->SetFont('Arial','B',15);
    // Move to the right
    $this->Cell(80);
    // Title
    $this->Cell(30,10,'Cotton University','C');
    // Line break
    $this->Ln(10);
}

// Page footer
function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
    $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
}

function PageBody(){
  $name = $_SESSION["full_name"];
  $name = 'Report generated by: '.ucwords($name);
  $date = 'Generated on: '.date("d/m/Y");
  $department = 'Department: '.$_POST["department"];

  $this->SetFont('Arial','BU',14);
  $this->Cell(200,10,'Report on CL',0,0,'C');
  $this->Ln(10);
  $this->SetFont('Arial','B',12);
  $this->Cell(200,10,$name);
  $this->Ln(5);
  $this->Cell(200,10,$date);
  $this->Ln(5);
  $this->Cell(200,10,$department);
  $this->Ln(10);
}

  // Load data
function LoadData($conn)
{
    $data = array();
    $department = $_POST["department"];
    $i = 0;

    $query = "SELECT id,full_name,username,cl_left FROM admin
              WHERE department = '{$department}'
              UNION ALL SELECT id,full_name,username,cl_left FROM USER
              WHERE department = '{$department}' ";
    // $query = "SELECT admin.full_name,admin.username,admin.cl_left,SUM(admin_history.cl_days_leave) AS cl_used ,admin_history.status,admin.department
    //           FROM admin_history INNER JOIN admin
    //           ON (admin.id = admin_history.user_id)
    //           GROUP BY admin_history.user_id
    //           HAVING admin.department = '{$department}' AND admin_history.status='approved'
    //           UNION ALL
    //           SELECT user.full_name,user.username,user.cl_left, SUM(history.cl_days_leave) AS cl_used, history.status,user.department
    //           FROM history INNER JOIN user
    //           ON (user.id = history.user_id)
    //           GROUP BY history.user_id
    //           HAVING user.department = '{$department}' AND history.status='approved'";

    $result=mysqli_query($conn,$query);
    $number_of_rows = mysqli_num_rows($result);
    while($row = mysqli_fetch_assoc($result)){
      $i++;
      $id = $row["id"];
      $name = ucwords($row["full_name"]);
      $username = $row["username"];
      $cl_left = $row["cl_left"];
      $cl_used = 0;
      // $cl_used = $row["cl_used"];

      if($i == 1){
        $query1 = "SELECT SUM(cl_days_leave) AS cl_used FROM admin_history WHERE user_id='{$id}' AND status='approved'";

      }else{
        $query1 = "SELECT SUM(cl_days_leave) AS cl_used FROM history WHERE user_id='{$id}' AND status='approved'";
      }
      $get_result = mysqli_query($conn,$query1);
      while($row1 = mysqli_fetch_assoc($get_result)){
          if(is_null($row1["cl_used"])){
            $cl_used = 0;
          }else{
            $cl_used = $row1["cl_used"];
          }

      }

      $temp_array = array();
      array_push($temp_array, $i, $name, $username, $cl_left,$cl_used);
      array_push($data, $temp_array);
      unset($temp_array);
    }

    return $data;

}

  function ImprovedTable($header, $data)
  {

      // Column widths
      $w = array(15,60,35,30,30);

      // Header
      for($i=0;$i<count($header);$i++){
        $this->Cell($w[$i],7,$header[$i],1,0,'C');
      }

      $this->Ln();
      // Data
      foreach($data as $row)
      {
          $this->Cell($w[0],6,$row[0],1,0,'C');
          $this->Cell($w[1],6,$row[1],1,0);
          $this->Cell($w[2],6,$row[2],1,0);
          $this->Cell($w[3],6,$row[3],1,0,'C');
          $this->Cell($w[4],6,$row[4],1,0,'C');
          //$this->Cell($w[4],6,$row[4],1,0,'C');

          $this->Ln();
      }
      // // Closing line
      $this->Cell(array_sum($w),0,'','T');
  }
}

  $pdf = new PDF();
  $pdf->AliasNbPages();
  // Column headings
  $header = array("Sl No.","Name","Username","CL Left","CL Used");
  // Data loading
  $data = $pdf->LoadData($connection);

  $pdf->AddPage();
  $pdf->PageBody();

  //create table
  $pdf->SetFont('Arial','',12);
  $pdf->ImprovedTable($header,$data);

  $pdf->Output();

 ?>
