<?php

  require_once("../FPDF/fpdf.php");
  require_once("../db.php");
  session_start();
  //error_reporting(E_WARNING);

class PDF extends FPDF {

  // Page header
function Header()
{

    // Arial bold 15
    $this->SetFont('Arial','B',15);
    // Move to the right
    $this->Cell(80);
    // Title
    $this->Cell(30,10,'Cotton University','C');
    // Line break
    $this->Ln(10);
}

// Page footer
function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
    $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
}

function PageBody(){
  $year = $_POST["year"];
  $name = $_SESSION["full_name"];
  $name = 'Report generated by: '.ucwords($name);
  $date = 'Generated on: '.date("d/m/Y");
  $history = "Application History on ".$year;
  $this->SetFont('Arial','BU',14);
  $this->Cell(200,10,'Report on CL',0,0,'C');
  $this->Ln(10);
  $this->SetFont('Arial','B',12);
  $this->Cell(200,10,$name);
  $this->Ln(5);
  $this->Cell(200,10,$date);
  $this->SetFont('Arial','B',12);
  $this->Ln(5);
  $this->Cell(200,10,$history,0,0,'C');
  $this->Ln(10);
  $this->SetFont('Arial','B',12);
}

  // format date
  function FormatDate($date){
    $splitTimeStamp = explode(" ",$date);
    $date = $splitTimeStamp[0];
    $time = $splitTimeStamp[1];
    $time_in_12_hour_format  = date("g:i a", strtotime($time));
    $format_date = $date."(".$time_in_12_hour_format.")";
    return $format_date;
  }

  // Load data
function LoadData($conn)
{
    $data = array();
    $i = 0;
    $user_id = $_SESSION["user_id"] ;
    $year = $_POST["year"];
    if( isset($_SESSION['loggedinAdmin']) && $_SESSION['loggedinAdmin']){
      $query = "SELECT * FROM admin_history WHERE user_id='{$user_id}'AND YEAR(from_date)='{$year}' ORDER BY from_date";
    }else{
      $query = "SELECT * FROM history WHERE user_id='{$user_id}'AND YEAR(from_date)='{$year}' ORDER BY from_date";
    }


    $result=mysqli_query($conn,$query);
    $number_of_rows = mysqli_num_rows($result);
    while($row = mysqli_fetch_assoc($result)){
      $i++;
      $from_date = $row["from_date"];
      $to_date = $row["to_date"];
      $half_day = $row["half_day"];
      $apply_time = $row["apply_time"];
      $admin_check_time = $row["admin_check_time"];
      $status = $row["status"];

      //****************
      $from_date = str_replace('/', '-', $from_date);
      $to_date = str_replace('/', '-', $to_date);
      //****************

      // Leave period
      $from_date = date("M d", strtotime($from_date));
      if($to_date != "0000-00-00"){
        $to_date = date("M d", strtotime($to_date));
        $leave_period = $from_date." - ".$to_date;
      }else{
        if(is_null($half_day) || empty($half_day)){
          $leave_period = $from_date;
        }else{

          $leave_period = $from_date." (".ucwords($half_day).")";
        }

      }

      // Applied Time
      $apply_time  = $this->FormatDate($apply_time);

      // Approved Time
      if($admin_check_time == "0000-00-00 00:00:00"){
          $admin_check_time = "Not Check";
      }else{
          $admin_check_time = $this->FormatDate($admin_check_time);
      }

      // status
      $status = ucwords($status);

      //push values into the array
      $temp_array = array();
      array_push($temp_array,$i,$leave_period,$apply_time,$admin_check_time,$status);

      array_push($data, $temp_array);
      unset($temp_array);
    }

    return $data;

}

  function ImprovedTable($header, $data)
  {

      // Column widths
      $w = array(15,50,50,50, 20);
      // Header
      for($i=0;$i<count($header);$i++){
        $this->Cell($w[$i],7,$header[$i],1,0,'C');
      }

      $this->Ln();
      // Data
      foreach($data as $row)
      {
          $this->Cell($w[0],6,$row[0],1,0,'C');
          $this->Cell($w[1],6,$row[1],1,0,'LR');
          $this->Cell($w[2],6,$row[2],1,0,'LR');
          $this->Cell($w[3],6,$row[3],1,0,'LR');
          $this->Cell($w[4],6,$row[4],1,0,'LR');
          $this->Ln();
      }
      // // Closing line
      $this->Cell(array_sum($w),0,'','T');
  }
}

  $pdf = new PDF();
  $pdf->AliasNbPages();
  // Column headings
  $header = array("Sl No.","Leave Period","Applied Time","Approved Time","Status");
  // Data loading
  $data = $pdf->LoadData($connection);

  $pdf->AddPage();
  $pdf->PageBody();

  //create table
  $pdf->SetFont('Arial','',12);
  $pdf->ImprovedTable($header,$data);

  $pdf->Output();

 ?>
